version: '3.3'

services:
  database:
    image: postgres:10.17
    restart: always
    container_name: 'postgres_sandbox'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: 'lab_moedas'
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5436:5432'
volumes:
  pg-data:
